--Add New User
--Inserts a new user into the database

--ALTER TABLE ACCOUNT DISABLE CONSTRAINT PK_ACCOUNT;

--INSERT INTO ACCOUNT (USERNAME,PASSWORD, IS_ADMIN, IS_SELLER) VALUES ('johngreg','password0123', '0', '0');

--ALTER TABLE ACCOUNT ENABLE CONSTRAINT PK_ACCOUNT;


--ALTER TABLE CUSTOMER DISABLE CONSTRAINT FK_CUSTOMER_TO_ACCOUNT;
--ALTER TABLE CUSTOMER DISABLE CONSTRAINT PK_CUSTOMER;


--INSERT INTO CUSTOMER (USERNAME,PHONE, EMAIL,FNAME, LNAME) VALUES ('johngreg', '1111111111','example@example.com','John', 'Greg' );

--ALTER TABLE CUSTOMER ENABLE CONSTRAINT FK_CUSTOMER_TO_ACCOUNT;
--ALTER TABLE CUSTOMER ENABLE CONSTRAINT PK_CUSTOMER;

