--View Sales Summary Report
CREATE OR REPLACE VIEW SALES_SUMMARY_REPORT_View AS

SELECT 
A.ITEM_CATEGORY,
A.ITEM_ID, 
A.ITEM_NAME,
B.MAXIMUM_BID_LIMIT,
B.MAXIMUM_BID_LIMIT *0.05 AS "COMMISSION"

FROM (AUCTION A JOIN BID B ON A.ITEM_ID = B.AUCTION_ID);
--WHERE STATUS = 'SOLD';  --Im not sure how to do this yet